### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by mbtamuli** [infracloudio/k8s-helm-tf#1]
https://github.com/infracloudio/k8s-helm-tf/blob/25eeedf4613af3c1ae7f5f29d9e9e38349fba7fb/k8s-do-tf/scripts/master.sh#L27

The link is broken. Maybe it should be https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by harshal-shah** [comment]
thanks for raising. 
This is fixed 
https://github.com/infracloudio/k8s-helm-tf/commit/5b97bc93fa063499ef1f43968595458e870599b1
